name: Pull Request Integration
on:
  pull_request:
    types:
      - opened
      - synchronized
      - reopened
    branches-ignore:
      - main

permissions: read-all

jobs:
  runs-on: ubuntu-latest
  permissions:
    contents: read
    pull-requests: write
  steps:
    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Build Filter
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          app:
            - '**/app/**'

    - name: Set up Python
      if: steps.changes.outputs.app == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      if: steps.changes.outputs.app == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flake8
      if: steps.changes.outputs.app == 'true'
      run: flake8 app/ --max-line-length=120 --extend-ignore=E203,W503

    - name: Run isort
      if: steps.changes.outputs.app == 'true'
      run: isort --check-only app/

    - name: Run Mypy
      if: steps.changes.outputs.app == 'true'
      run: mypy app/

    - name: Run Tests
      if: steps.changes.outputs.app == 'true'
      run: pytest tests/ --cov=app --cov-report=xml
