on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions: read-all

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build Filter
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            app:
              - '**/src/**'

      - name: Install Dependencies
        if: steps.changes.outputs.app == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        if: steps.changes.outputs.app == 'true'
        run: |
          pytest src/tests/ --cov=src/app/ --cov-report=term-missing --cov-report=html --cov-report=xml
